# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trax.trax.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=trax.trax.models.get_now)),
                ('next_call', models.DateTimeField(blank=True, null=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('crontab', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('channel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='timer',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterModelOptions(
            name='timergroup',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_date',
            field=models.DateTimeField(default=trax.trax.models.get_now),
        ),
        migrations.AlterField(
            model_name='timergroup',
            name='creation_date',
            field=models.DateTimeField(default=trax.trax.models.get_now),
        ),
        migrations.AlterUniqueTogether(
            name='timergroup',
            unique_together=set([('slug', 'user')]),
        ),
    ]
