# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MattermostIncomingWebhook',
            fields=[
                ('incomingwebhook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.IncomingWebhook')),
            ],
            options={
                'abstract': False,
            },
            bases=('integrations.incomingwebhook',),
        ),
    ]
